### ISSUE TITLE
Using repo2docker

### ISSUE THREAD

**Issue by jgomezdans** [UCL-EO/uclgeog_msc_core#1]
Might be easier to just use repo2docker which automatically builds up the docker image (it's what's behind binder), using e.g. `environment.yml` and `postBuild` and whatever else.

**Comment by profLewis** [comment]
That’s interesting ...

Professor Philip Lewis, UCL

**Comment by profLewis** [comment]
Trying it out at the moment!

**Comment by profLewis** [comment]
✅
